import { bundles, getProduct, products } from '../data/products.js';
import { faqs, reasons, reviews } from '../data/content.js';

const bottle = (product, extra='') => `<div class="bottle-art ${extra}" style="--product:${product.color}" role="img" aria-label="Bottle of ${product.name}"><span class="bottle-cap"></span><span class="bottle-neck"></span><span class="bottle-body"><span class="bottle-label"><b>MOLTEN</b><em>${product.glyph}</em><small>${product.name}</small></span></span></div>`;
const addButton = (product, label='Add to cart') => `<button class="button button--dark add-to-cart" data-product="${product.id}"><span>${label}</span><b>$${product.price}</b></button>`;
const productLink = product => `product.html?id=${product.id}`;

const bundleSection = () => `<section class="bundle section" id="bundles" aria-labelledby="bundle-title">
  <div class="eyebrow">Save your future dinner</div>
  <div class="bundle-grid">
    <div><h2 id="bundle-title" class="display">Stack the<br>bottles.</h2><p class="lede">More sauce, less emergency grocery-store compromise.</p></div>
    <div class="bundle-builder" data-bundle-builder>
      <div class="segmented" role="radiogroup" aria-label="Bundle size">${bundles.map((b,i)=>`<button role="radio" aria-checked="${i===0}" data-bundle="${b.id}">${b.size} pack</button>`).join('')}</div>
      <div class="bundle-bottles" aria-hidden="true">${products.slice(0,3).map(p=>bottle(p,'bottle-art--small')).join('')}</div>
      <div class="bundle-meta"><div><span data-bundle-name>${bundles[0].name}</span><strong data-bundle-price>$${bundles[0].price}</strong><small data-bundle-save>Save $${bundles[0].savings}</small></div><button class="button button--dark" data-add-bundle>Add bundle</button></div>
    </div>
  </div>
</section>`;

const reviewsSection = () => `<section class="reviews section" aria-labelledby="reviews-title"><h2 id="reviews-title" class="display display--outline">REVIEWS</h2><div class="reviews-track" data-marquee>${[...reviews,...reviews].map((r,i)=>`<article class="review" ${i>=reviews.length?'aria-hidden="true"':''}><span>“</span><p>${r.quote}</p><b>${r.name}</b></article>`).join('')}</div><div class="sr-only">${reviews.map(r=>`${r.name}: ${r.quote}`).join(' ')}</div></section>`;

const home = () => `<main id="main" data-home>
  <section class="hero" style="--accent:${products[0].color}">
    <canvas class="hero-webgl" aria-hidden="true"></canvas>
    <div class="hero-noise" aria-hidden="true"></div>
    <div class="hero-copy"><p class="eyebrow">Fruit first. Fire second.</p><h1><span class="hero-line">The sauce</span><span class="hero-line">that makes</span><span class="hero-line hero-line--accent">plain food</span><span class="hero-line hero-line--accent">panic.</span></h1></div>
    <div class="hero-stage" data-hero-stage>${bottle(products[0])}<span class="orbit orbit--one">${products[0].glyph}</span><span class="orbit orbit--two">✦</span></div>
    <div class="hero-controls"><button class="circle-button" data-hero-prev aria-label="Previous flavor">←</button><div><small>Flavor <span data-hero-number>01</span> / 04</small><strong data-hero-name>${products[0].name}</strong></div><button class="circle-button" data-hero-next aria-label="Next flavor">→</button></div>
    <a class="button hero-cta" href="shop.html">Get sauced <span>↗</span></a><p class="hero-note" data-hero-copy>${products[0].description}</p>
  </section>
  <section class="statement section"><div class="statement-copy"><span class="eyebrow">Nothing suspicious in the bottle</span><h2>We cook with ingredients your mouth already knows.</h2><p>Real fruit. Roasted peppers. Sharp vinegar. No laboratory aftertaste, no flavor fog, no polite little condiment energy.</p></div><figure class="campaign-image reveal-image"><img src="/src/assets/molten-mouth-campaign.png" alt="Original Molten Mouth sauce bottle surrounded by fruit, garlic, and peppers" width="1200" height="1500"><figcaption>One bottle. Several excellent decisions.</figcaption></figure></section>
  <section class="benefits section" aria-label="What is inside"><div class="benefit-intro"><span class="eyebrow">The short no-list</span><h2 class="display">LESS<br>WEIRD.</h2></div><div class="benefit-stack">${[['No corn syrup','Sweet should taste like fruit, not fluorescent math.','✕'],['No seed oils','We build body with produce, not anonymous industrial slick.','◌'],['No fake stuff','If our chef cannot say it at normal speed, it stays out.','?!'],['Gluten-free','A wide-open guest list for the grill.','GF']].map((b,i)=>`<article class="benefit" style="--benefit:${products[i].color}"><span>${b[2]}</span><div><small>0${i+1}</small><h3>${b[0]}</h3><p>${b[1]}</p></div></article>`).join('')}</div></section>
  <section class="showcase section" id="products"><div class="showcase-sticky"><span class="eyebrow">Choose your accomplice</span><h2 class="display">PICK<br>A FIGHT.</h2><p data-showcase-copy>${products[0].description}</p></div><div class="product-takes">${products.map((p,i)=>`<article class="product-take" style="--product:${p.color};--product-ink:${p.ink}" data-product-take="${p.id}"><div class="product-take-top"><span>0${i+1}</span><span>Heat ${'●'.repeat(p.heat)}${'○'.repeat(5-p.heat)}</span></div>${bottle(p)}<div class="product-take-copy"><p>${p.kicker}</p><h3>${p.name}</h3><div>${addButton(p)}<a href="${productLink(p)}" class="text-link">Meet the bottle ↗</a></div></div></article>`).join('')}</div></section>
  <section class="story section"><div class="story-image"><img src="/src/assets/molten-mouth-campaign.png" alt="Sauce-making ingredients arranged around a dark glass bottle" width="1200" height="1500"><span class="badge">Built in a<br>real kitchen<br>✦</span></div><div class="story-copy"><span class="eyebrow">Why we exist</span><h2>Because “fine” is a terrible flavor.</h2>${reasons.map(r=>`<article class="reason"><b>${r[0]}</b><h3>${r[1]}</h3><p>${r[2]}</p></article>`).join('')}<a class="button button--dark" href="about.html">Our whole story</a></div></section>
  <section class="process-film section"><div class="film-frame" data-film><img src="/src/assets/molten-mouth-campaign.png" alt="Molten Mouth bottle and fresh ingredients" width="1200" height="1500"><canvas aria-hidden="true"></canvas><button class="film-toggle" aria-pressed="false"><span>▶</span><b>Play kitchen loop</b></button></div><div><span class="eyebrow">Heat, chop, taste, repeat</span><h2 class="display">COOKED,<br>NOT<br>CONJURED.</h2><p>Our process has steam, stained aprons, loud opinions, and a spoon that never gets a day off.</p><a class="text-link" href="about.html">Meet the tiny team ↗</a></div></section>
  ${bundleSection()}${reviewsSection()}
</main>`;

const shop = () => `<main id="main"><section class="page-hero page-hero--shop"><p class="eyebrow">Four bottles. No background characters.</p><h1>Sauce made<br><span>from real</span><br>ingredients.</h1>${bottle(products[1],'hero-bottle')}</section><section class="shop-controls section" aria-label="Product filters"><div class="filter-buttons"><button class="is-active" data-heat="all">All heat</button><button data-heat="mild">Mild</button><button data-heat="hot">Hot</button></div><label>Sort<select data-sort><option value="featured">Featured</option><option value="price-low">Price: low</option><option value="price-high">Price: high</option><option value="heat">Heat</option></select></label><button class="text-link" data-reset>Reset</button></section><section class="shop-list section" data-shop-list>${products.map((p,i)=>`<article class="shop-row" data-heat-value="${p.heat}" data-price="${p.price}" data-id="${p.id}" style="--product:${p.color}"><div class="shop-row-number">0${i+1}</div><div class="shop-row-visual">${bottle(p)}</div><div class="shop-row-copy"><span>${p.kicker}</span><h2>${p.name}</h2><p>${p.description}</p><div class="heat">Heat ${'●'.repeat(p.heat)}${'○'.repeat(5-p.heat)}</div><div>${addButton(p)}<a href="${productLink(p)}" class="text-link">View product ↗</a></div></div></article>`).join('')}<p class="empty-state" hidden>Nothing matches that level of bravery. Try another filter.</p></section><section class="ticker"><div>PAIRS WITH · BAD IDEAS · GOOD FRIENDS · MIDNIGHT EGGS · BURNT ENDS · LEFTOVERS · </div></section>${bundleSection()}${reviewsSection()}</main>`;

const product = () => { const id = new URLSearchParams(location.search).get('id'); const p=getProduct(id); const related=products.filter(x=>x.id!==p.id).slice(0,3); return `<main id="main" style="--page-product:${p.color}"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="shop.html">Shop</a><span>/</span><span>${p.name}</span></nav><section class="product-detail"><div class="product-gallery" data-gallery style="--product:${p.color}"><div class="product-photo is-active" data-view="front">${bottle(p)}</div><div class="product-photo product-photo--back" data-view="back">${bottle({...p,name:'Ingredients + trouble'})}</div><button class="circle-button gallery-prev" aria-label="Previous product view">←</button><button class="circle-button gallery-next" aria-label="Next product view">→</button><div class="gallery-thumbs"><button class="is-active" data-gallery-view="front">Front</button><button data-gallery-view="back">Back</button></div></div><div class="product-info"><span class="eyebrow">${p.kicker}</span><h1>${p.name}</h1><p class="lede">${p.description}</p><div class="heat"><span>Heat level</span><b>${'●'.repeat(p.heat)}${'○'.repeat(5-p.heat)}</b></div><div class="detail-cards"><article><h2>Taste profile</h2><p>${p.ingredients.join(' · ')}</p></article><article><h2>Pairs with</h2><p>${p.pairings.join(' · ')}</p></article></div><div class="buy-row"><div class="quantity"><button data-qty-minus aria-label="Decrease quantity">−</button><input data-qty value="1" inputmode="numeric" aria-label="Quantity"><button data-qty-plus aria-label="Increase quantity">+</button></div>${addButton(p)}</div><details><summary>Ingredients</summary><p>${p.ingredients.join(', ')}, sea salt, cane sugar, spices. Placeholder recipe for demonstration.</p></details><details><summary>Nutrition</summary><p>Nutrition facts will be supplied with final production packaging.</p></details><details><summary>Shipping</summary><p>Usually leaves our kitchen in two business days, packed to survive enthusiastic delivery vans.</p></details></div></section><section class="related section"><span class="eyebrow">Other useful trouble</span><h2 class="display">NEXT<br>BOTTLE.</h2><div class="related-grid">${related.map(x=>`<a href="${productLink(x)}" style="--product:${x.color}">${bottle(x,'bottle-art--small')}<span>${x.name}</span></a>`).join('')}</div></section>${bundleSection()}</main>`; };

const about = () => `<main id="main"><section class="about-hero"><div class="scatter scatter--a">✹</div><div class="scatter scatter--b">▲</div><h1><span>BUILDING</span><span>THE</span><span>FLAVOR.</span></h1><p>We started with a saucepan, a notebook, and the mild suspicion that most sauce had given up.</p></section><section class="about-collage section"><img src="/src/assets/molten-mouth-campaign.png" alt="Fresh peppers, garlic, fruit, and a sauce bottle" width="1200" height="1500"><div><span class="eyebrow">Our unfair advantage</span><h2>We treat sauce like food.</h2><p>That means roasting, tasting, reducing, arguing, tasting again, and stopping before the ingredients lose their names.</p></div></section><section class="philosophy section"><h2 class="display">THE SUPERPOWER<br>IS PAYING<br>ATTENTION.</h2><div><p class="lede">Founder and chef Mina Vale spent a decade building restaurant sauces that had to work on the first bite and the last.</p><p>Molten Mouth brings that same balance to a bottle: fruit for shape, acid for clarity, heat for momentum, and salt for the little lightbulb over your tongue.</p></div></section><section class="origin section"><div class="origin-sticky"><img src="/src/assets/molten-mouth-campaign.png" alt="Molten Mouth campaign bottle" width="1200" height="1500"><span>Kitchen no. 04</span></div><div>${reasons.map(r=>`<article><b>${r[0]}</b><h2>${r[1]}</h2><p>${r[2]}</p></article>`).join('')}</div></section><section class="values section"><span class="eyebrow">What stays true</span><div>${['Taste before trend','People before scale','Useful before precious','A joke, never a gimmick'].map((v,i)=>`<article><b>0${i+1}</b><h3>${v}</h3></article>`).join('')}</div><a class="button button--dark" href="shop.html">Taste the evidence</a></section></main>`;

const wholesale = () => `<main id="main"><section class="wholesale-hero"><div><span class="eyebrow">For shelves and menus with standards</span><h1>PUT SOME<br>PERSONALITY<br>ON THE SHELF.</h1><p class="lede">Small-batch sauce, clean margins, responsive humans, and packaging that does not whisper.</p></div><div class="bottle-cluster">${products.slice(0,3).map((p,i)=>bottle(p,`cluster-${i}`)).join('')}</div></section><section class="partner section">${[['WHY','Fruit-forward recipes people remember.'],['WHAT','Case packs, samples, menu support, and quick reorders.'],['WHO','Independent grocers, restaurants, bottle shops, and brave gift stores.']].map(x=>`<article><span>${x[0]}</span><h2>${x[1]}</h2></article>`).join('')}</section>${reviewsSection()}<section class="form-section section"><div><span class="eyebrow">Make shelf space</span><h2 class="display">LET’S<br>TALK<br>SAUCE.</h2><p>Tell us what you run and how fast your customers eat.</p></div><form class="big-form" data-form="wholesale" novalidate>${[['name','Full name','text'],['business','Business name','text'],['email','Email','email'],['phone','Phone','tel'],['website','Website','url'],['location','Location','text'],['volume','Estimated monthly volume','number']].map(f=>`<label>${f[1]}<input name="${f[0]}" type="${f[2]}" required><span class="field-error"></span></label>`).join('')}<label>Business type<select name="type" required><option value="">Choose one</option><option>Retail</option><option>Restaurant</option><option>Distributor</option><option>Other</option></select><span class="field-error"></span></label><label>How did you hear about us?<select name="source" required><option value="">Choose one</option><option>Friend</option><option>Event</option><option>Social</option><option>Search</option></select><span class="field-error"></span></label><label class="full">Message<textarea name="message" rows="5" required></textarea><span class="field-error"></span></label><label class="check full"><input type="checkbox" name="consent" required> I agree to be contacted about wholesale ordering.<span class="field-error"></span></label><button class="button button--dark full" type="submit">Send the good paperwork</button><p class="form-status full" role="status"></p></form></section></main>`;

const faq = () => `<main id="main"><section class="faq-hero"><span class="orbit">?</span><h1>FREQUENTLY<br>ASKED<br><em>QUESTIONS.</em></h1><p>Everything except the secret spoon count.</p></section><section class="faq-list section">${faqs.map((f,i)=>`<article class="faq-item" id="${f[0]}"><h2><button aria-expanded="false" aria-controls="answer-${f[0]}"><span><small>0${i+1}</small>${f[1]}</span><b>+</b></button></h2><div id="answer-${f[0]}" class="faq-answer" hidden><p>${f[2]}</p></div></article>`).join('')}</section></main>`;

const contact = () => `<main id="main"><section class="contact section"><div class="contact-copy"><span class="burst">SAY<br>HELLO<br>↘</span><h1>CONTACT.</h1><p class="lede">Questions, order hiccups, love notes, productive disagreements.</p><a href="mailto:hello@moltenmouth.example">hello@moltenmouth.example</a><p>Philadelphia-ish, USA<br>Instagram · TikTok · Very loud kitchens</p></div><form class="big-form" data-form="contact" novalidate><label>Name<input name="name" required><span class="field-error"></span></label><label>Email<input name="email" type="email" required><span class="field-error"></span></label><label>Subject<input name="subject" required><span class="field-error"></span></label><label>Order number <small>optional</small><input name="order"></label><label class="full">Message<textarea name="message" rows="8" required></textarea><span class="field-error"></span></label><label class="honeypot" aria-hidden="true">Leave empty<input name="website" tabindex="-1" autocomplete="off"></label><button class="button button--dark full" type="submit">Send it across the kitchen</button><p class="form-status full" role="status"></p></form></section></main>`;

const checkout = () => `<main id="main"><section class="checkout section"><div><span class="eyebrow">Checkout placeholder</span><h1>Almost<br>yours.</h1><p>This production-ready placeholder intentionally does not collect payment details. Connect your commerce provider here.</p><a class="text-link" href="shop.html">Keep shopping ←</a></div><aside><h2>Your order</h2><div data-checkout-items></div><div class="checkout-total"><span>Subtotal</span><b data-checkout-total>$0.00</b></div><button class="button button--dark" disabled>Payment provider required</button></aside></section></main>`;
const notFound = () => `<main id="main"><section class="not-found"><span>404</span><h1>The sauce<br>escaped.</h1><p>We checked the fridge. This page is not in there either.</p><a class="button" href="index.html">Back to the good stuff</a></section></main>`;

export const pageTemplates = {home, shop, product, about, wholesale, faq, contact, checkout, '404':notFound};
